// === CONFIGURABLE CONSTANTS ===
const MIN_STRIVE_DISTANCE = 14;
const MAX_ACCELERATION_RATE = 0.8;
const ACCELERATION_DURATION = 30;
const MIN_REACTION_TIME = 200;
const MAX_REACTION_TIME = 800;
const POST_EAT_SLOWDOWN = 0.3;
const NEIGHBOR_RADIUS = 150;
const POINTER_REPEL_RADIUS = 120;
const POINTER_REPEL_FORCE = 0.9;
const STARVATION_WARNING = 300000;
const STARVATION_CRITICAL = 330000;

// === REPRODUCTION & GROWTH CONFIG ===
const FOOD_FOR_OFFSPRING = 5;
const OFFSPRING_COUNT = 2;
const MIN_FISH_SIZE = 8;
const MAX_FISH_SIZE = 20;
const NN_MUTATION_RATE = 0.05;

// === SPOOK SETTINGS ===
const SPOOK_DURATION = 30;
const SPOOK_ACCEL_BOOST = 1.5;
const SPOOK_RADIUS_BOOST = 2;

// === VISUALIZATION TOGGLES ===
let showEatRadius = false;
let showFoodTargets = false;
